spring.application.name=zelo

spring.datasource.url=jdbc:mysql://localhost:3306/zelo?useSSL=false&serverTimezone=America/Bahia
spring.datasource.username=root
spring.datasource.password=wjnb16102007#

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080